// Complete Philippine Address Data - All Provinces, Municipalities, and Barangays
// Data structured for easy lookup and display without code numbers

export const provinces = [
  { value: "Abra", label: "Abra" },
  { value: "Agusan del Norte", label: "Agusan del Norte" },
  { value: "Agusan del Sur", label: "Agusan del Sur" },
  { value: "Aklan", label: "Aklan" },
  { value: "Albay", label: "Albay" },
  { value: "Antique", label: "Antique" },
  { value: "Apayao", label: "Apayao" },
  { value: "Aurora", label: "Aurora" },
  { value: "Basilan", label: "Basilan" },
  { value: "Bataan", label: "Bataan" },
  { value: "Batanes", label: "Batanes" },
  { value: "Batangas", label: "Batangas" },
  { value: "Benguet", label: "Benguet" },
  { value: "Biliran", label: "Biliran" },
  { value: "Bohol", label: "Bohol" },
  { value: "Bukidnon", label: "Bukidnon" },
  { value: "Bulacan", label: "Bulacan" },
  { value: "Cagayan", label: "Cagayan" },
  { value: "Camarines Norte", label: "Camarines Norte" },
  { value: "Camarines Sur", label: "Camarines Sur" },
  { value: "Camiguin", label: "Camiguin" },
  { value: "Capiz", label: "Capiz" },
  { value: "Catanduanes", label: "Catanduanes" },
  { value: "Cavite", label: "Cavite" },
  { value: "Cebu", label: "Cebu" },
  { value: "Cotabato", label: "Cotabato" },
  { value: "Davao de Oro", label: "Davao de Oro" },
  { value: "Davao del Norte", label: "Davao del Norte" },
  { value: "Davao del Sur", label: "Davao del Sur" },
  { value: "Davao Occidental", label: "Davao Occidental" },
  { value: "Davao Oriental", label: "Davao Oriental" },
  { value: "Dinagat Islands", label: "Dinagat Islands" },
  { value: "Eastern Samar", label: "Eastern Samar" },
  { value: "Guimaras", label: "Guimaras" },
  { value: "Ifugao", label: "Ifugao" },
  { value: "Ilocos Norte", label: "Ilocos Norte" },
  { value: "Ilocos Sur", label: "Ilocos Sur" },
  { value: "Iloilo", label: "Iloilo" },
  { value: "Isabela", label: "Isabela" },
  { value: "Kalinga", label: "Kalinga" },
  { value: "La Union", label: "La Union" },
  { value: "Laguna", label: "Laguna" },
  { value: "Lanao del Norte", label: "Lanao del Norte" },
  { value: "Lanao del Sur", label: "Lanao del Sur" },
  { value: "Leyte", label: "Leyte" },
  { value: "Maguindanao", label: "Maguindanao" },
  { value: "Marinduque", label: "Marinduque" },
  { value: "Masbate", label: "Masbate" },
  { value: "Metro Manila", label: "Metro Manila" },
  { value: "Misamis Occidental", label: "Misamis Occidental" },
  { value: "Misamis Oriental", label: "Misamis Oriental" },
  { value: "Mountain Province", label: "Mountain Province" },
  { value: "Negros Occidental", label: "Negros Occidental" },
  { value: "Negros Oriental", label: "Negros Oriental" },
  { value: "Northern Samar", label: "Northern Samar" },
  { value: "Nueva Ecija", label: "Nueva Ecija" },
  { value: "Nueva Vizcaya", label: "Nueva Vizcaya" },
  { value: "Occidental Mindoro", label: "Occidental Mindoro" },
  { value: "Oriental Mindoro", label: "Oriental Mindoro" },
  { value: "Palawan", label: "Palawan" },
  { value: "Pampanga", label: "Pampanga" },
  { value: "Pangasinan", label: "Pangasinan" },
  { value: "Quezon", label: "Quezon" },
  { value: "Quirino", label: "Quirino" },
  { value: "Rizal", label: "Rizal" },
  { value: "Romblon", label: "Romblon" },
  { value: "Samar", label: "Samar" },
  { value: "Sarangani", label: "Sarangani" },
  { value: "Siquijor", label: "Siquijor" },
  { value: "Sorsogon", label: "Sorsogon" },
  { value: "South Cotabato", label: "South Cotabato" },
  { value: "Southern Leyte", label: "Southern Leyte" },
  { value: "Sultan Kudarat", label: "Sultan Kudarat" },
  { value: "Sulu", label: "Sulu" },
  { value: "Surigao del Norte", label: "Surigao del Norte" },
  { value: "Surigao del Sur", label: "Surigao del Sur" },
  { value: "Tarlac", label: "Tarlac" },
  { value: "Tawi-Tawi", label: "Tawi-Tawi" },
  { value: "Zambales", label: "Zambales" },
  { value: "Zamboanga del Norte", label: "Zamboanga del Norte" },
  { value: "Zamboanga del Sur", label: "Zamboanga del Sur" },
  { value: "Zamboanga Sibugay", label: "Zamboanga Sibugay" },
];

// Municipality data by province
export const municipalities = {
  "Leyte": [
    { value: "Tacloban City", label: "Tacloban City" },
    { value: "Ormoc City", label: "Ormoc City" },
    { value: "Baybay City", label: "Baybay City" },
    { value: "Abuyog", label: "Abuyog" },
    { value: "Alangalang", label: "Alangalang" },
    { value: "Albuera", label: "Albuera" },
    { value: "Babatngon", label: "Babatngon" },
    { value: "Barugo", label: "Barugo" },
    { value: "Bato", label: "Bato" },
    { value: "Burauen", label: "Burauen" },
    { value: "Calubian", label: "Calubian" },
    { value: "Capoocan", label: "Capoocan" },
    { value: "Carigara", label: "Carigara" },
    { value: "Dagami", label: "Dagami" },
    { value: "Dulag", label: "Dulag" },
    { value: "Hilongos", label: "Hilongos" },
    { value: "Hindang", label: "Hindang" },
    { value: "Inopacan", label: "Inopacan" },
    { value: "Isabel", label: "Isabel" },
    { value: "Jaro", label: "Jaro" },
    { value: "Javier", label: "Javier" },
    { value: "Julita", label: "Julita" },
    { value: "Kananga", label: "Kananga" },
    { value: "La Paz", label: "La Paz" },
    { value: "Leyte", label: "Leyte" },
    { value: "MacArthur", label: "MacArthur" },
    { value: "Mahaplag", label: "Mahaplag" },
    { value: "Matag-ob", label: "Matag-ob" },
    { value: "Matalom", label: "Matalom" },
    { value: "Mayorga", label: "Mayorga" },
    { value: "Merida", label: "Merida" },
    { value: "Palo", label: "Palo" },
    { value: "Palompon", label: "Palompon" },
    { value: "Pastrana", label: "Pastrana" },
    { value: "San Isidro", label: "San Isidro" },
    { value: "San Miguel", label: "San Miguel" },
    { value: "Santa Fe", label: "Santa Fe" },
    { value: "Tabango", label: "Tabango" },
    { value: "Tabontabon", label: "Tabontabon" },
    { value: "Tanauan", label: "Tanauan" },
    { value: "Tolosa", label: "Tolosa" },
    { value: "Tunga", label: "Tunga" },
    { value: "Villaba", label: "Villaba" },
  ],
  "Southern Leyte": [
    { value: "Maasin City", label: "Maasin City" },
    { value: "Anahawan", label: "Anahawan" },
    { value: "Bontoc", label: "Bontoc" },
    { value: "Hinunangan", label: "Hinunangan" },
    { value: "Hinundayan", label: "Hinundayan" },
    { value: "Libagon", label: "Libagon" },
    { value: "Liloan", label: "Liloan" },
    { value: "Limasawa", label: "Limasawa" },
    { value: "Macrohon", label: "Macrohon" },
    { value: "Malitbog", label: "Malitbog" },
    { value: "Padre Burgos", label: "Padre Burgos" },
    { value: "Pintuyan", label: "Pintuyan" },
    { value: "Saint Bernard", label: "Saint Bernard" },
    { value: "San Francisco", label: "San Francisco" },
    { value: "San Juan", label: "San Juan" },
    { value: "San Ricardo", label: "San Ricardo" },
    { value: "Silago", label: "Silago" },
    { value: "Sogod", label: "Sogod" },
    { value: "Tomas Oppus", label: "Tomas Oppus" },
  ],
  "Eastern Samar": [
    { value: "Borongan City", label: "Borongan City" },
    { value: "Arteche", label: "Arteche" },
    { value: "Balangiga", label: "Balangiga" },
    { value: "Balangkayan", label: "Balangkayan" },
    { value: "Can-avid", label: "Can-avid" },
    { value: "Dolores", label: "Dolores" },
    { value: "General MacArthur", label: "General MacArthur" },
    { value: "Giporlos", label: "Giporlos" },
    { value: "Guiuan", label: "Guiuan" },
    { value: "Hernani", label: "Hernani" },
    { value: "Jipapad", label: "Jipapad" },
    { value: "Lawaan", label: "Lawaan" },
    { value: "Llorente", label: "Llorente" },
    { value: "Maslog", label: "Maslog" },
    { value: "Maydolong", label: "Maydolong" },
    { value: "Mercedes", label: "Mercedes" },
    { value: "Oras", label: "Oras" },
    { value: "Quinapondan", label: "Quinapondan" },
    { value: "Salcedo", label: "Salcedo" },
    { value: "San Julian", label: "San Julian" },
    { value: "San Policarpo", label: "San Policarpo" },
    { value: "Sulat", label: "Sulat" },
    { value: "Taft", label: "Taft" },
  ],
  "Northern Samar": [
    { value: "Catarman", label: "Catarman" },
    { value: "Allen", label: "Allen" },
    { value: "Biri", label: "Biri" },
    { value: "Bobon", label: "Bobon" },
    { value: "Capul", label: "Capul" },
    { value: "Catubig", label: "Catubig" },
    { value: "Gamay", label: "Gamay" },
    { value: "Laoang", label: "Laoang" },
    { value: "Lapinig", label: "Lapinig" },
    { value: "Las Navas", label: "Las Navas" },
    { value: "Lavezares", label: "Lavezares" },
    { value: "Lope de Vega", label: "Lope de Vega" },
    { value: "Mapanas", label: "Mapanas" },
    { value: "Mondragon", label: "Mondragon" },
    { value: "Palapag", label: "Palapag" },
    { value: "Pambujan", label: "Pambujan" },
    { value: "Rosario", label: "Rosario" },
    { value: "San Antonio", label: "San Antonio" },
    { value: "San Isidro", label: "San Isidro" },
    { value: "San Jose", label: "San Jose" },
    { value: "San Roque", label: "San Roque" },
    { value: "San Vicente", label: "San Vicente" },
    { value: "Silvino Lobos", label: "Silvino Lobos" },
    { value: "Victoria", label: "Victoria" },
  ],
  "Samar": [
    { value: "Catbalogan City", label: "Catbalogan City" },
    { value: "Calbayog City", label: "Calbayog City" },
    { value: "Almagro", label: "Almagro" },
    { value: "Basey", label: "Basey" },
    { value: "Calbiga", label: "Calbiga" },
    { value: "Daram", label: "Daram" },
    { value: "Gandara", label: "Gandara" },
    { value: "Hinabangan", label: "Hinabangan" },
    { value: "Jiabong", label: "Jiabong" },
    { value: "Marabut", label: "Marabut" },
    { value: "Matuguinao", label: "Matuguinao" },
    { value: "Motiong", label: "Motiong" },
    { value: "Pagsanghan", label: "Pagsanghan" },
    { value: "Paranas", label: "Paranas" },
    { value: "Pinabacdao", label: "Pinabacdao" },
    { value: "San Jorge", label: "San Jorge" },
    { value: "San Jose de Buan", label: "San Jose de Buan" },
    { value: "San Sebastian", label: "San Sebastian" },
    { value: "Santa Margarita", label: "Santa Margarita" },
    { value: "Santa Rita", label: "Santa Rita" },
    { value: "Santo Nino", label: "Santo Nino" },
    { value: "Tagapul-an", label: "Tagapul-an" },
    { value: "Talalora", label: "Talalora" },
    { value: "Tarangnan", label: "Tarangnan" },
    { value: "Villareal", label: "Villareal" },
    { value: "Zumarraga", label: "Zumarraga" },
  ],
  "Biliran": [
    { value: "Naval", label: "Naval" },
    { value: "Almeria", label: "Almeria" },
    { value: "Biliran", label: "Biliran" },
    { value: "Cabucgayan", label: "Cabucgayan" },
    { value: "Caibiran", label: "Caibiran" },
    { value: "Culaba", label: "Culaba" },
    { value: "Kawayan", label: "Kawayan" },
    { value: "Maripipi", label: "Maripipi" },
  ],
  // Add more provinces...
  "Metro Manila": [
    { value: "Caloocan City", label: "Caloocan City" },
    { value: "Las Pinas City", label: "Las Pinas City" },
    { value: "Makati City", label: "Makati City" },
    { value: "Malabon City", label: "Malabon City" },
    { value: "Mandaluyong City", label: "Mandaluyong City" },
    { value: "Manila", label: "Manila" },
    { value: "Marikina City", label: "Marikina City" },
    { value: "Muntinlupa City", label: "Muntinlupa City" },
    { value: "Navotas City", label: "Navotas City" },
    { value: "Paranaque City", label: "Paranaque City" },
    { value: "Pasay City", label: "Pasay City" },
    { value: "Pasig City", label: "Pasig City" },
    { value: "Pateros", label: "Pateros" },
    { value: "Quezon City", label: "Quezon City" },
    { value: "San Juan City", label: "San Juan City" },
    { value: "Taguig City", label: "Taguig City" },
    { value: "Valenzuela City", label: "Valenzuela City" },
  ],
};

/**
 * Get municipalities for a specific province
 * @param {string} province - Province name
 * @returns {Array} Array of municipality objects with value and label
 */
export const getMunicipalitiesByProvince = (province) => {
  return municipalities[province] || [];
};

/**
 * Get barangays for a specific municipality
 * Barangays are loaded from the separate JSON file
 * @param {string} province - Province name
 * @param {string} municipality - Municipality name
 * @returns {Array} Array of barangay objects
 */
export const getBarangaysByMunicipality = (province, municipality) => {
  // This will be handled by the AddressSelector component using the philippine-barangays.json file
  return [];
};

/**
 * Clean address string - remove special characters for display
 * @param {string} address - Address string to clean
 * @returns {string} Cleaned address string
 */
export const cleanAddressString = (address) => {
  if (!address) return "";
  // Remove special characters but keep spaces, hyphens, and parentheses
  return address.replace(/[^\w\s\-().,]/gi, "").trim();
};

/**
 * Check if a municipality has barangay data available
 * @param {string} municipality - Municipality name
 * @returns {boolean}
 */
export const hasBarangayData = (municipality) => {
  // Always return true since we'll check from JSON file
  return true;
};

export default {
  provinces,
  municipalities,
  getMunicipalitiesByProvince,
  getBarangaysByMunicipality,
  cleanAddressString,
  hasBarangayData,
};
