// Philippine Address Data - Province, Municipality, Barangay
// This is a sample dataset focusing on Leyte and nearby provinces

export const provinces = [
  { value: "Leyte", label: "Leyte" },
  { value: "Southern Leyte", label: "Southern Leyte" },
  { value: "Eastern Samar", label: "Eastern Samar" },
  { value: "Northern Samar", label: "Northern Samar" },
  { value: "Samar (Western Samar)", label: "Samar (Western Samar)" },
  { value: "Biliran", label: "Biliran" },
];

export const municipalities = {
  "Leyte": [
    { value: "Tacloban City", label: "Tacloban City" },
    { value: "Ormoc City", label: "Ormoc City" },
    { value: "Baybay City", label: "Baybay City" },
    { value: "Abuyog", label: "Abuyog" },
    { value: "Alangalang", label: "Alangalang" },
    { value: "Albuera", label: "Albuera" },
    { value: "Babatngon", label: "Babatngon" },
    { value: "Barugo", label: "Barugo" },
    { value: "Bato", label: "Bato" },
    { value: "Burauen", label: "Burauen" },
    { value: "Calubian", label: "Calubian" },
    { value: "Capoocan", label: "Capoocan" },
    { value: "Carigara", label: "Carigara" },
    { value: "Dagami", label: "Dagami" },
    { value: "Dulag", label: "Dulag" },
    { value: "Hilongos", label: "Hilongos" },
    { value: "Hindang", label: "Hindang" },
    { value: "Inopacan", label: "Inopacan" },
    { value: "Isabel", label: "Isabel" },
    { value: "Jaro", label: "Jaro" },
    { value: "Javier", label: "Javier" },
    { value: "Julita", label: "Julita" },
    { value: "Kananga", label: "Kananga" },
    { value: "La Paz", label: "La Paz" },
    { value: "Leyte", label: "Leyte" },
    { value: "MacArthur", label: "MacArthur" },
    { value: "Mahaplag", label: "Mahaplag" },
    { value: "Matag-ob", label: "Matag-ob" },
    { value: "Matalom", label: "Matalom" },
    { value: "Mayorga", label: "Mayorga" },
    { value: "Merida", label: "Merida" },
    { value: "Palo", label: "Palo" },
    { value: "Palompon", label: "Palompon" },
    { value: "Pastrana", label: "Pastrana" },
    { value: "San Isidro", label: "San Isidro" },
    { value: "San Miguel", label: "San Miguel" },
    { value: "Santa Fe", label: "Santa Fe" },
    { value: "Tabango", label: "Tabango" },
    { value: "Tabontabon", label: "Tabontabon" },
    { value: "Tanauan", label: "Tanauan" },
    { value: "Tolosa", label: "Tolosa" },
    { value: "Tunga", label: "Tunga" },
    { value: "Villaba", label: "Villaba" },
  ],
  "Southern Leyte": [
    { value: "Maasin City", label: "Maasin City" },
    { value: "Anahawan", label: "Anahawan" },
    { value: "Bontoc", label: "Bontoc" },
    { value: "Hinunangan", label: "Hinunangan" },
    { value: "Hinundayan", label: "Hinundayan" },
    { value: "Libagon", label: "Libagon" },
    { value: "Liloan", label: "Liloan" },
    { value: "Limasawa", label: "Limasawa" },
    { value: "Macrohon", label: "Macrohon" },
    { value: "Malitbog", label: "Malitbog" },
    { value: "Padre Burgos", label: "Padre Burgos" },
    { value: "Pintuyan", label: "Pintuyan" },
    { value: "Saint Bernard", label: "Saint Bernard" },
    { value: "San Francisco", label: "San Francisco" },
    { value: "San Juan", label: "San Juan" },
    { value: "San Ricardo", label: "San Ricardo" },
    { value: "Silago", label: "Silago" },
    { value: "Sogod", label: "Sogod" },
    { value: "Tomas Oppus", label: "Tomas Oppus" },
  ],
  "Eastern Samar": [
    { value: "Borongan City", label: "Borongan City" },
    { value: "Arteche", label: "Arteche" },
    { value: "Balangiga", label: "Balangiga" },
    { value: "Balangkayan", label: "Balangkayan" },
    { value: "Can-avid", label: "Can-avid" },
    { value: "Dolores", label: "Dolores" },
    { value: "General MacArthur", label: "General MacArthur" },
    { value: "Giporlos", label: "Giporlos" },
    { value: "Guiuan", label: "Guiuan" },
    { value: "Hernani", label: "Hernani" },
    { value: "Jipapad", label: "Jipapad" },
    { value: "Lawaan", label: "Lawaan" },
    { value: "Llorente", label: "Llorente" },
    { value: "Maslog", label: "Maslog" },
    { value: "Maydolong", label: "Maydolong" },
    { value: "Mercedes", label: "Mercedes" },
    { value: "Oras", label: "Oras" },
    { value: "Quinapondan", label: "Quinapondan" },
    { value: "Salcedo", label: "Salcedo" },
    { value: "San Julian", label: "San Julian" },
    { value: "San Policarpo", label: "San Policarpo" },
    { value: "Sulat", label: "Sulat" },
    { value: "Taft", label: "Taft" },
  ],
  "Northern Samar": [
    { value: "Catarman", label: "Catarman" },
    { value: "Allen", label: "Allen" },
    { value: "Biri", label: "Biri" },
    { value: "Bobon", label: "Bobon" },
    { value: "Capul", label: "Capul" },
    { value: "Catubig", label: "Catubig" },
    { value: "Gamay", label: "Gamay" },
    { value: "Laoang", label: "Laoang" },
    { value: "Lapinig", label: "Lapinig" },
    { value: "Las Navas", label: "Las Navas" },
    { value: "Lavezares", label: "Lavezares" },
    { value: "Lope de Vega", label: "Lope de Vega" },
    { value: "Mapanas", label: "Mapanas" },
    { value: "Mondragon", label: "Mondragon" },
    { value: "Palapag", label: "Palapag" },
    { value: "Pambujan", label: "Pambujan" },
    { value: "Rosario", label: "Rosario" },
    { value: "San Antonio", label: "San Antonio" },
    { value: "San Isidro", label: "San Isidro" },
    { value: "San Jose", label: "San Jose" },
    { value: "San Roque", label: "San Roque" },
    { value: "San Vicente", label: "San Vicente" },
    { value: "Silvino Lobos", label: "Silvino Lobos" },
    { value: "Victoria", label: "Victoria" },
  ],
  "Samar (Western Samar)": [
    { value: "Catbalogan City", label: "Catbalogan City" },
    { value: "Calbayog City", label: "Calbayog City" },
    { value: "Almagro", label: "Almagro" },
    { value: "Basey", label: "Basey" },
    { value: "Calbiga", label: "Calbiga" },
    { value: "Daram", label: "Daram" },
    { value: "Gandara", label: "Gandara" },
    { value: "Hinabangan", label: "Hinabangan" },
    { value: "Jiabong", label: "Jiabong" },
    { value: "Marabut", label: "Marabut" },
    { value: "Matuguinao", label: "Matuguinao" },
    { value: "Motiong", label: "Motiong" },
    { value: "Pagsanghan", label: "Pagsanghan" },
    { value: "Paranas", label: "Paranas" },
    { value: "Pinabacdao", label: "Pinabacdao" },
    { value: "San Jorge", label: "San Jorge" },
    { value: "San Jose de Buan", label: "San Jose de Buan" },
    { value: "San Sebastian", label: "San Sebastian" },
    { value: "Santa Margarita", label: "Santa Margarita" },
    { value: "Santa Rita", label: "Santa Rita" },
    { value: "Santo Niño", label: "Santo Niño" },
    { value: "Tagapul-an", label: "Tagapul-an" },
    { value: "Talalora", label: "Talalora" },
    { value: "Tarangnan", label: "Tarangnan" },
    { value: "Villareal", label: "Villareal" },
    { value: "Zumarraga", label: "Zumarraga" },
  ],
  "Biliran": [
    { value: "Naval", label: "Naval" },
    { value: "Almeria", label: "Almeria" },
    { value: "Biliran", label: "Biliran" },
    { value: "Cabucgayan", label: "Cabucgayan" },
    { value: "Caibiran", label: "Caibiran" },
    { value: "Culaba", label: "Culaba" },
    { value: "Kawayan", label: "Kawayan" },
    { value: "Maripipi", label: "Maripipi" },
  ],
};

export const barangays = {
  // Leyte Province - Sample municipalities with barangays
  "Tacloban City": [
    { value: "Abucay", label: "Abucay" },
    { value: "Apitong", label: "Apitong" },
    { value: "Bagacay", label: "Bagacay" },
    { value: "Barangay 1", label: "Barangay 1" },
    { value: "Barangay 2", label: "Barangay 2" },
    { value: "Barangay 3", label: "Barangay 3" },
    { value: "Barangay 4", label: "Barangay 4" },
    { value: "Barangay 5", label: "Barangay 5" },
    { value: "Cabalawan", label: "Cabalawan" },
    { value: "Caibaan", label: "Caibaan" },
    { value: "Calanipawan", label: "Calanipawan" },
    { value: "Calvario", label: "Calvario" },
    { value: "Candahug", label: "Candahug" },
    { value: "Diit", label: "Diit" },
    { value: "New Kawayan", label: "New Kawayan" },
    { value: "Old Kawayan", label: "Old Kawayan" },
    { value: "Palo", label: "Palo" },
    { value: "San Jose", label: "San Jose" },
    { value: "Santa Elena", label: "Santa Elena" },
    { value: "Sagkahan", label: "Sagkahan" },
  ],
  "Ormoc City": [
    { value: "Alta Vista", label: "Alta Vista" },
    { value: "Bagong Buhay", label: "Bagong Buhay" },
    { value: "Can-adieng", label: "Can-adieng" },
    { value: "Can-untog", label: "Can-untog" },
    { value: "Cogon", label: "Cogon" },
    { value: "Dolores", label: "Dolores" },
    { value: "Donghol", label: "Donghol" },
    { value: "Hibunawan", label: "Hibunawan" },
    { value: "Ipil", label: "Ipil" },
    { value: "Liberty", label: "Liberty" },
    { value: "Linao", label: "Linao" },
    { value: "Mabini", label: "Mabini" },
    { value: "Margen", label: "Margen" },
    { value: "Nasunogan", label: "Nasunogan" },
    { value: "Punta", label: "Punta" },
    { value: "San Antonio", label: "San Antonio" },
    { value: "San Isidro", label: "San Isidro" },
    { value: "San Jose", label: "San Jose" },
    { value: "San Pablo", label: "San Pablo" },
    { value: "Valencia", label: "Valencia" },
  ],
  "Baybay City": [
    { value: "Amguhan", label: "Amguhan" },
    { value: "Ampihanon", label: "Ampihanon" },
    { value: "Balao", label: "Balao" },
    { value: "Biasong", label: "Biasong" },
    { value: "Bitanhuan", label: "Bitanhuan" },
    { value: "Candadam", label: "Candadam" },
    { value: "Caridad", label: "Caridad" },
    { value: "Ciabo", label: "Ciabo" },
    { value: "Gabas", label: "Gabas" },
    { value: "Guadalupe", label: "Guadalupe" },
    { value: "Hibunawan", label: "Hibunawan" },
    { value: "Higuloan", label: "Higuloan" },
    { value: "Imelda", label: "Imelda" },
    { value: "Kilim", label: "Kilim" },
    { value: "Makinhas", label: "Makinhas" },
    { value: "Palhi", label: "Palhi" },
    { value: "Pangasungan", label: "Pangasungan" },
    { value: "Punta", label: "Punta" },
    { value: "San Agustin", label: "San Agustin" },
    { value: "Villa Solidaridad", label: "Villa Solidaridad" },
  ],
  "San Jorge": [
    { value: "Buenavista", label: "Buenavista" },
    { value: "Calapi", label: "Calapi" },
    { value: "Crossing", label: "Crossing" },
    { value: "Guintagbucan", label: "Guintagbucan" },
    { value: "Inoraguran", label: "Inoraguran" },
    { value: "Lalawigan", label: "Lalawigan" },
    { value: "Mabuhay", label: "Mabuhay" },
    { value: "Mabini", label: "Mabini" },
    { value: "Malinao", label: "Malinao" },
    { value: "Manloy", label: "Manloy" },
    { value: "Poblacion 1", label: "Poblacion 1" },
    { value: "Poblacion 2", label: "Poblacion 2" },
    { value: "Poblacion 3", label: "Poblacion 3" },
    { value: "Poblacion 4", label: "Poblacion 4" },
    { value: "Poblacion 5", label: "Poblacion 5" },
    { value: "San Isidro", label: "San Isidro" },
    { value: "San Miguel", label: "San Miguel" },
    { value: "San Roque", label: "San Roque" },
    { value: "Santa Cruz", label: "Santa Cruz" },
    { value: "Santo Niño", label: "Santo Niño" },
  ],
  "Albuera": [
    { value: "Balugo", label: "Balugo" },
    { value: "Benowangan", label: "Benowangan" },
    { value: "Cambalading", label: "Cambalading" },
    { value: "Damulaan", label: "Damulaan" },
    { value: "Ermita", label: "Ermita" },
    { value: "Guinciaman", label: "Guinciaman" },
    { value: "Mahagna", label: "Mahagna" },
    { value: "Poblacion", label: "Poblacion" },
    { value: "Salvacion", label: "Salvacion" },
    { value: "San Pedro", label: "San Pedro" },
    { value: "Salvacion", label: "Salvacion" },
    { value: "Sta. Cruz", label: "Sta. Cruz" },
  ],
  
  // Southern Leyte - Sample municipalities
  "Maasin City": [
    { value: "Abgao", label: "Abgao" },
    { value: "Acasia", label: "Acasia" },
    { value: "Asuncion", label: "Asuncion" },
    { value: "Bactul", label: "Bactul" },
    { value: "Bagtican", label: "Bagtican" },
    { value: "Batuan", label: "Batuan" },
    { value: "Bato", label: "Bato" },
    { value: "Combado", label: "Combado" },
    { value: "Ibarra", label: "Ibarra" },
    { value: "Laboon", label: "Laboon" },
    { value: "Libertad", label: "Libertad" },
    { value: "Mabini", label: "Mabini" },
    { value: "Mantahan", label: "Mantahan" },
    { value: "Rizal", label: "Rizal" },
    { value: "San Isidro", label: "San Isidro" },
    { value: "San Rafael", label: "San Rafael" },
    { value: "Santa Cruz", label: "Santa Cruz" },
    { value: "Tunga-tunga", label: "Tunga-tunga" },
  ],
  "Sogod": [
    { value: "Benit", label: "Benit" },
    { value: "Cabalquinto", label: "Cabalquinto" },
    { value: "Concepcion", label: "Concepcion" },
    { value: "Dagsa", label: "Dagsa" },
    { value: "Hibod-hibod", label: "Hibod-hibod" },
    { value: "Kahupian", label: "Kahupian" },
    { value: "Kanangkaan", label: "Kanangkaan" },
    { value: "Kauswagan", label: "Kauswagan" },
    { value: "Libas", label: "Libas" },
    { value: "Poblacion", label: "Poblacion" },
    { value: "San Francisco", label: "San Francisco" },
    { value: "San Isidro", label: "San Isidro" },
    { value: "San Juan", label: "San Juan" },
    { value: "San Miguel", label: "San Miguel" },
    { value: "Santa Maria", label: "Santa Maria" },
  ],

  // Samar (Western Samar) - Municipalities with barangays
  "Santa Margarita": [
    { value: "Balud", label: "Balud" },
    { value: "Cagsumje", label: "Cagsumje" },
    { value: "Ilo", label: "Ilo" },
    { value: "Inoraguiao", label: "Inoraguiao" },
    { value: "Lambao", label: "Lambao" },
    { value: "Magsohong", label: "Magsohong" },
    { value: "Napuro", label: "Napuro" },
    { value: "Palale", label: "Palale" },
    { value: "Solsogon", label: "Solsogon" },
  ],
  "Gandara": [
    { value: "Adela Heights", label: "Adela Heights" },
    { value: "Arong 1", label: "Arong 1" },
    { value: "Arong 2", label: "Arong 2" },
    { value: "Balocawe", label: "Balocawe" },
    { value: "Bangahon", label: "Bangahon" },
    { value: "Beslig", label: "Beslig" },
    { value: "Buao", label: "Buao" },
    { value: "Bunyagan", label: "Bunyagan" },
    { value: "Burabod I", label: "Burabod I" },
    { value: "Burabod II", label: "Burabod II" },
    { value: "Calirocan", label: "Calirocan" },
    { value: "Canhumawid", label: "Canhumawid" },
    { value: "Caparangasan", label: "Caparangasan" },
    { value: "Caranas", label: "Caranas" },
    { value: "Carmona", label: "Carmona" },
    { value: "Casab-ahan", label: "Casab-ahan" },
    { value: "Casandig", label: "Casandig" },
    { value: "Catorse de Agosto", label: "Catorse de Agosto" },
    { value: "Caugbusan", label: "Caugbusan" },
    { value: "Concepcion", label: "Concepcion" },
    { value: "Diaz", label: "Diaz" },
    { value: "Dumalo-ong", label: "Dumalo-ong" },
    { value: "Elcano", label: "Elcano" },
    { value: "Gerali", label: "Gerali" },
    { value: "Gereganan", label: "Gereganan" },
    { value: "Giaboc", label: "Giaboc" },
    { value: "Hampton", label: "Hampton" },
    { value: "Hetebac", label: "Hetebac" },
    { value: "Himamaloto", label: "Himamaloto" },
    { value: "Hinayagan", label: "Hinayagan" },
    { value: "Hinugacan", label: "Hinugacan" },
    { value: "Hiparayan", label: "Hiparayan" },
    { value: "Jasminez", label: "Jasminez" },
    { value: "Lungib", label: "Lungib" },
    { value: "Mabuhay", label: "Mabuhay" },
    { value: "Macugo", label: "Macugo" },
    { value: "Malayog", label: "Malayog" },
    { value: "Marcos", label: "Marcos" },
    { value: "Minda", label: "Minda" },
    { value: "Nacube", label: "Nacube" },
    { value: "Nalihugan", label: "Nalihugan" },
    { value: "Napalisan", label: "Napalisan" },
    { value: "Natimonan", label: "Natimonan" },
    { value: "Ngoso", label: "Ngoso" },
    { value: "Palambrag", label: "Palambrag" },
    { value: "Palanas", label: "Palanas" },
    { value: "Piñaplata", label: "Piñaplata" },
    { value: "Pizarro", label: "Pizarro" },
    { value: "Pologon", label: "Pologon" },
    { value: "Purog", label: "Purog" },
    { value: "Rawis", label: "Rawis" },
    { value: "Rizal", label: "Rizal" },
    { value: "Samoyao", label: "Samoyao" },
    { value: "San Agustin", label: "San Agustin" },
    { value: "San Antonio", label: "San Antonio" },
    { value: "San Enrique", label: "San Enrique" },
    { value: "San Francisco", label: "San Francisco" },
    { value: "San Isidro", label: "San Isidro" },
    { value: "San Jose", label: "San Jose" },
    { value: "San Miguel", label: "San Miguel" },
    { value: "San Pelayo", label: "San Pelayo" },
    { value: "San Ramon", label: "San Ramon" },
    { value: "Santa Elena", label: "Santa Elena" },
    { value: "Santo Niño", label: "Santo Niño" },
    { value: "Senibaran", label: "Senibaran" },
    { value: "Sidmon", label: "Sidmon" },
    { value: "Tagnao", label: "Tagnao" },
    { value: "Tambongan", label: "Tambongan" },
    { value: "Tawiran", label: "Tawiran" },
    { value: "Tigbawon", label: "Tigbawon" },
  ],
  "Catbalogan City": [
    { value: "Aguinaldo", label: "Aguinaldo" },
    { value: "Bacayawan", label: "Bacayawan" },
    { value: "Bagongon", label: "Bagongon" },
    { value: "Barangay 1 (Poblacion)", label: "Barangay 1 (Poblacion)" },
    { value: "Barangay 2 (Poblacion)", label: "Barangay 2 (Poblacion)" },
    { value: "Barangay 3 (Poblacion)", label: "Barangay 3 (Poblacion)" },
    { value: "Barangay 4 (Poblacion)", label: "Barangay 4 (Poblacion)" },
    { value: "Barangay 5 (Poblacion)", label: "Barangay 5 (Poblacion)" },
    { value: "Barangay 6 (Poblacion)", label: "Barangay 6 (Poblacion)" },
    { value: "Barangay 7 (Poblacion)", label: "Barangay 7 (Poblacion)" },
    { value: "Barangay 8 (Poblacion)", label: "Barangay 8 (Poblacion)" },
    { value: "Barangay 9 (Poblacion)", label: "Barangay 9 (Poblacion)" },
    { value: "Buena Suerte", label: "Buena Suerte" },
    { value: "Cagudalo", label: "Cagudalo" },
    { value: "Can-adieng", label: "Can-adieng" },
    { value: "Canduhao", label: "Canduhao" },
    { value: "Carlosa", label: "Carlosa" },
    { value: "Hi-otag", label: "Hi-otag" },
    { value: "Imelda", label: "Imelda" },
    { value: "Maulong", label: "Maulong" },
    { value: "Mercedes", label: "Mercedes" },
    { value: "Pawing", label: "Pawing" },
    { value: "San Andres", label: "San Andres" },
    { value: "San Pablo", label: "San Pablo" },
    { value: "San Vicente", label: "San Vicente" },
  ],
  "Calbayog City": [
    { value: "Acedillo", label: "Acedillo" },
    { value: "Awang", label: "Awang" },
    { value: "Bagacay", label: "Bagacay" },
    { value: "Balud", label: "Balud" },
    { value: "Barangay 1 (Poblacion)", label: "Barangay 1 (Poblacion)" },
    { value: "Barangay 2 (Poblacion)", label: "Barangay 2 (Poblacion)" },
    { value: "Barangay 3 (Poblacion)", label: "Barangay 3 (Poblacion)" },
    { value: "Barangay 4 (Poblacion)", label: "Barangay 4 (Poblacion)" },
    { value: "Binaliw", label: "Binaliw" },
    { value: "Bugtong", label: "Bugtong" },
    { value: "Cag-abaca", label: "Cag-abaca" },
    { value: "Calingcaguing", label: "Calingcaguing" },
    { value: "Capoocan", label: "Capoocan" },
    { value: "Danao", label: "Danao" },
    { value: "Gadgaran", label: "Gadgaran" },
    { value: "Hampangan", label: "Hampangan" },
    { value: "Hamorawon", label: "Hamorawon" },
    { value: "Hibatang", label: "Hibatang" },
    { value: "Hinabay", label: "Hinabay" },
    { value: "Langoyon", label: "Langoyon" },
    { value: "Mancol", label: "Mancol" },
    { value: "Mantaong", label: "Mantaong" },
    { value: "Matobato", label: "Matobato" },
    { value: "Obrero", label: "Obrero" },
    { value: "Oquendo", label: "Oquendo" },
    { value: "Rawis", label: "Rawis" },
    { value: "San Joaquin", label: "San Joaquin" },
    { value: "Tinambacan", label: "Tinambacan" },
  ],
  "Basey": [
    { value: "Amandayehan", label: "Amandayehan" },
    { value: "Bacubac", label: "Bacubac" },
    { value: "Baloog", label: "Baloog" },
    { value: "Barangay 1 (Poblacion)", label: "Barangay 1 (Poblacion)" },
    { value: "Barangay 2 (Poblacion)", label: "Barangay 2 (Poblacion)" },
    { value: "Barangay 3 (Poblacion)", label: "Barangay 3 (Poblacion)" },
    { value: "Basiao", label: "Basiao" },
    { value: "Buenavista", label: "Buenavista" },
    { value: "Burgos", label: "Burgos" },
    { value: "Cambayan", label: "Cambayan" },
    { value: "Cancelada", label: "Cancelada" },
    { value: "Guindaponan", label: "Guindaponan" },
    { value: "Hibaca-an", label: "Hibaca-an" },
    { value: "Loog", label: "Loog" },
    { value: "Marcos", label: "Marcos" },
    { value: "Mercado", label: "Mercado" },
    { value: "Palaypay", label: "Palaypay" },
    { value: "Salvacion", label: "Salvacion" },
    { value: "San Antonio", label: "San Antonio" },
    { value: "San Fernando", label: "San Fernando" },
  ],

  // Add more barangays as needed for other municipalities
};

/**
 * Get municipalities for a specific province
 * @param {string} province - Province name
 * @returns {Array} Array of municipality objects
 */
export const getMunicipalitiesByProvince = (province) => {
  return municipalities[province] || [];
};

/**
 * Get barangays for a specific municipality
 * @param {string} municipality - Municipality name
 * @returns {Array} Array of barangay objects
 */
export const getBarangaysByMunicipality = (municipality) => {
  return barangays[municipality] || [];
};

/**
 * Check if a municipality has barangay data
 * @param {string} municipality - Municipality name
 * @returns {boolean}
 */
export const hasBarangayData = (municipality) => {
  return !!barangays[municipality] && barangays[municipality].length > 0;
};

export default {
  provinces,
  municipalities,
  barangays,
  getMunicipalitiesByProvince,
  getBarangaysByMunicipality,
  hasBarangayData,
};
